UI_CONFIG:
  WINDOW_WIDTH: 600
  WINDOW_HEIGHT: 700 # Including some extra space for title, scores etc.
  BG_COLOUR: "WHITE"
  TITLE: 
    TEXT: "2048"
    COLOUR: "BLACK"
    TOP_PADDING: 20
    FONT: 
      NAME: Arial
      SIZE: 16
  SCORE:
    SECTION_HEIGHT: 40
    COLOUR: "BLACK"
    BOTTOM_PADDING: 10
    FONT:
      NAME: Arial
      SIZE: 12
  TILE:
    PADDING: 10
    FONT:
      NAME: Arial
      SIZE: 12
  BOARD:
    PADDING: 10
    FILL: "LIGHT_GREY"
    BORDER:
      FILL: "BLACK"
      THICKNESS: 3
    GRID:
      FILL: "BLACK"
      THICKNESS: 3
  GAME_OVER_LABEL:
    TEXT: "GAME OVER"
    FILL: "WHITE"
    BORDER:
      FILL: "RED"
      THICKNESS: 5
    FONT:
      NAME: Arial
      SIZE: 24
      STYLE: bold
      COLOUR: "RED"

GAME_CONFIG:
  BOARD_DIM: 10
  FPS: 1
  SLEEP_PER_TIMESTEP: 1
  EPISODES_PER_RENDER: 20
  2_TILE_PROBABILITY: 0.9
  4_TILE_PROBABILITY: 0.1 # 1 - 2 tile probability
    
FILE_FOLDER_CONFIG:
  MODEL_FOLDER_PATH: "models"
  MODEL_NAME_PREFIX: "ai_model_"
  GAME_DATA_FOLDER_PATH: "data"
  SCORES_FILE_PATH: "data/game_scores.txt"

LOGS_CONFIG:
  LOGS_FOLDER_PATH: "logs"

MODEL_CONFIG:
  NUM_ACTIONS: 4
  
TRAINING_CONFIG: # Change during actual PROD
  REWARDS:
    MERGE: 15.0
    DOUBLE: 50.0
    WIN: 1000.0
    NEW_HIGH_SCORE: 500.0
    GAME_OVER: -1000.0
    ACTION: -10.0
  MAX_TRAINING_EPISODES: 2000
  MAX_TIMESTEPS_PER_EPISODE: 3000
  EPISODES_PER_CHECKPOINT: 100
  LEARNING_RATE: 0.0001
  REPLAY_MEMORY_SIZE: 256
  GAMMA: 0.99
  EPSILON_START: 1
  EPSILON_DECAY: 0.995
  EPSILON_END: 0.001
  TARGET_UPDATE_FREQUENCY: 1000 # Timesteps after which target network is updateds
  BATCH_SIZE: 64
  CLIP_GRADIENTS: 10
  PRINT_LOSS_EVERY: 100
  


