GAME_CONFIG:
  SLEEP_PER_TIMESTEP: 0.2
  BOARD_DIM: 11
  EPISODES_PER_RENDER: 20
    
DATA_CONFIG:
  DATA_FOLDER_PATH: src/data
  GAME_DATA_FOLDER: gamedata
  MODEL_DATA_FOLDER: modeldata

LOGS_CONFIG:
  LOGS_FOLDER_PATH: logs

MODEL_CONFIG:
  MODELS_FOLDER_PATH: src/models
  LEARNING_RATE: 0.0001
  OPTIMIZER: Adam

TRAINING_CONFIG:
  REWARDS:
    MERGE_TILES: 10
  MAX_TRAINING_EPISODES: 10000
  EPISODES_PER_CHECKPOINT: 100
  EXPLORATION_RATE: 0.999
  EXPLORATION_RATE_DECAY: 0.999
  EXPLORATION_RATE_MIN: 0

